sudo: required
services: 
    - docker

before_install:
    - docker build -t satendra1958/docker-react -f DockerFile.dev .

scripts:
    - docker run satendra1958/docker-react npm run test -- -- coverage