sudo: required
services: 
    - docker

before_install:
    - docker build -t satendra1958/docker-react -f Dockerfile.dev .
    - echo "BEFORE INSTALL START"
    - gem install bundler
    - echo "BEFORE INSTALL END"

script:
    - docker run satendra1958/docker-react npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker-react"
    env: "DockerReact-env"
    bucket-name: "elasticbeanstalk-us-east-2-109362314868"
    bucket-path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: 
        secure: "$AWS_SECRET_KEY"
    